### ISSUE TITLE
 ASNCDC.ADDTABLE not increment MAP_ID over 10

### ISSUE THREAD

**Issue by wolfgangbrandl** [debezium/debezium-connector-db2#17]
The line:
' ( SELECT CASE WHEN max(CAST(MAP_ID AS INT)) IS NULL THEN CAST(1 AS VARCHAR(10)) ELSE CAST(CAST(max(MAP_ID) AS INT) + 1 AS VARCHAR(10))  END AS MYINT from  ASNCDC.IBMSNAP_PRUNCNTL ) ' ||
should be corrected to:
' ( SELECT CASE WHEN max(CAST(MAP_ID AS INT)) IS NULL THEN CAST(1 AS VARCHAR(10)) ELSE CAST((max(CAST(MAP_ID AS INT)) + 1) AS VARCHAR(10))  END AS MYINT from  ASNCDC.IBMSNAP_PRUNCNTL ) '

**Comment by jpechane** [comment]
@wolfgangbrandl Hi, thanks for the report. Could you please raise regular Joira issue (sues.jboss.org/browse/DBZ) and also elaborate on more details? Thanks a lot

**Comment by wolfgangbrandl** [comment]
Please explain in more detail what kind of issue you want.
  I don't know what a joira issue is.
  Sorry.
  
  ----- Urspr&uuml;ngliche Nachricht -----
  Von: Jiri Pechanec ***@***.***>
  Datum: 29.03.2021 13:27
  An: debezium/debezium-connector-db2 ***@***.***>
  Kopie: Wolfgang Brandl ***@***.***>, Mention ***@***.***>
  Betreff: Re: [debezium/debezium-connector-db2] ASNCDC.ADDTABLE not increment MAP_ID over 10 (#17)
  &nbsp; >
