### ISSUE TITLE
pgrep does not exist for AIX

### ISSUE THREAD

**Issue by wolfgangbrandl** [debezium/debezium-connector-db2#18]
The line:
strcheck = sprintf(cmdstring, "pgrep -fx \"%s/sqllib/bin/asncap capture_schema=%s capture_server=%s\" > %s", szDb2path, asnService, dbname, tmpFileName);

is not working for AIX and piping let the function fail because of not allowed forking.
Have you another solution.

**Comment by jpechane** [comment]
@wolfgangbrandl See previous comment. Would you please also be so kind andcreate a general Jira issue describing all related AIX incmpatibilities?
Thanks a lot
