### ISSUE TITLE
db2 on zOS Support

### ISSUE THREAD

**Issue by thedh2152** [debezium/debezium-connector-db2#20]
Hello, just wondering - is there any plans to support db2 on zOS as well? Seems many of the SYS type tables are different from the Linux version of db2 used in the Debezium connection classes which determine tables with CCD enabled, etc. 

Thanks in advance!

**Comment by jpechane** [comment]
Unfortunately we don't have an access to zOS so it is quite difficult to provide the support :-(. For further questions or discussion please use our chat or mailing list. Thanks a lot!
