### ISSUE TITLE
Can this be installed in mainframe db2? <eom>

### ISSUE THREAD

**Issue by anborg** [debezium/debezium-connector-db2#31]

**Comment by gunnarmorling** [comment]
Hey @anborg, just seeing this. It could work, or it could not, we have not tested this in absence of a suitable testing environment. If you have the opportunity to do so, please let us know about any findings via the [mailing list](https://groups.google.com/g/debezium). Thanks!

That said, I'm going to close this issue and also disable issue functionality for this repo, as we use [Jira](https://issues.redhat.com/browse/DBZ) for issue tracking and aforementioned mailing list for discussion. It was an oversight to have issues enabled here. Thanks again!
